if (typeof instop === "undefined" || instop === null || instop === "") { return; } 
switch (instop) {

    case 0:
        var formattedText = oTextDirect.getText(); 
        break;

    case 1:
        var formattedText = oTextOneStop.getText() + ": " + instoplocs ; 
        break;

    default:
        var formattedText = instop + " " + oTextStops.getText() + ": " + instoplocs ; 
        break;

}

return formattedText;