var data = modeloFormHotelDetails.getData();
data.id = createBookingID();


getCacheoListHotelsSelected();


setTimeout(function() {

    ModelData.Add(oListHotelsSelected, data);
    setCacheoListHotelsSelected();

    jQuery.sap.require("sap.m.MessageBox");
    sap.m.MessageBox.show("Hotel added to your booking trip");

    oApp.backDetailToPage(oPageBlank);
    oApp.backMasterToPage(oPageSearch);

}, 1000);